### ISSUE TITLE
Is there a plain to work on this repo?

### ISSUE THREAD

**Issue by astronati** [cajames/vue-tag-manager#8]
Hi,

As user of your repo, I would like to know if there is a plan to work on it in order to improve it?

Thanks

**Comment by cajames** [comment]
Yep there is actually, it's served its purpose so far but I'll still be working on it. Is there a feature you're waiting for? Please feel free to submit PRs if you're able to contribute.

**Comment by cajames** [comment]
Please reopen if there are any issues with the current implementation.
